### ISSUE TITLE
[BUG] Can't download anything, and throws exception

### ISSUE THREAD

**Issue by cainy-a** [thesadru/animethemes-dl#11]
- Platform: `Windows 10` (also tested on Manjaro Linux and Repl.it)
- Python Version: `3.9.0`
- Extra Workaraounds: Remove the `#!/usr/bin/env python` line from `main.py` as this caused it to fail to import pySmartDl
---
EDIT: After some debugging in PyCharm it appears that the issue is when `SmartDL()` is called on line `227` in `downloader.py`

---
I'm attempting to download all themes from my Anilist, using the following command:
`py .\main.py --al Yellowsink -v C:\Users\caina\Documents\MEGA\Vids\Anime_OPs`
however it throws an exception and doesn't work:
```
[progress] initializing program
[get] getting data from anilist.co | 279ms
[get] getting data from themes.moe | 966ms
[parse] getting download data
[progress] started downloading
[download] Steins;Gate OP (Hacking to the Gate).webm
Traceback (most recent call last):
  File "C:\Users\caina\source\repos\animethemes-dl\main.py", line 163, in <module>
    batch_download(
  File "C:\Users\caina\source\repos\animethemes-dl\downloader.py", line 422, in batch_download
    download_multi_theme(download_data,webm_folder,mp3_folder)
  File "C:\Users\caina\source\repos\animethemes-dl\downloader.py", line 402, in download_multi_theme
    filename = download_chooser(mthd)
  File "C:\Users\caina\source\repos\animethemes-dl\downloader.py", line 381, in <lambda>
    download_theme(
  File "C:\Users\caina\source\repos\animethemes-dl\downloader.py", line 227, in download_theme
    obj = SmartDL(theme_data["mirrors"],filename,progress_bar=not Opts.Print.quiet)
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\site-packages\pySmartDL\pySmartDL.py", line 136, in __init__
    if not utils.is_HTTPRange_supported(self.url, timeout=self.timeout):
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\site-packages\pySmartDL\utils.py", line 100, in is_HTTPRange_supported
    fullsize = get_filesize(url, timeout=timeout)
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\site-packages\pySmartDL\utils.py", line 127, in get_filesize
    urlObj = urllib.request.urlopen(url, timeout=timeout)
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1346, in do_open
    r = h.getresponse()
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\caina\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by cainy-a** [comment]
OKAY TURNS OUT THEMES.MOE IS DOWN (`503 Service Unavailable`) SORRY!!!!
