### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by iggymeow** [thesadru/animethemes-dl#15]
* `Windows 10`
* `Python 3.8.0` 

I'm not very good at coding and I didn't really understand the documentation so I apologize in advance if I'm making some really obvious mistake.

 I'm trying to download some openings from my anilist but when I run the command
`animethemes-dl --al nya -v C:\Users\mateo\Documents\themes --smart --min-resolution 1080`
it results with
```
Traceback (most recent call last):
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\Scripts\animethemes-dl-script.py", line 11, in <module>
    load_entry_point('animethemes-dl==2.2.2.1', 'console_scripts', 'animethemes-dl')()
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\animethemes_dl\__init__.py", line 4, in <module>
    from .downloader import *
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\animethemes_dl\downloader.py", line 14, in <module>
    from .parsers import get_download_data
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\animethemes_dl\parsers\__init__.py", line 4, in <module>
    from .animelist import ANIMELISTSITES ,AniList, MyAnimeList
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\animethemes_dl\parsers\animelist.py", line 18, in <module>
    from .utils import Measure, add_url_kwargs
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\animethemes_dl\parsers\utils.py", line 9, in <module>
    def add_url_kwargs(url: str, kwargs: dict[str,Any]) -> str:
TypeError: 'type' object is not subscriptable
```
I'm not sure if my syntax is wrong, I've also tried to downloading openings using different parameters and even tried fixing it by installing it using git clone but they all result in the same `Traceback (most recent call last):
` thing

Any help would be appreciated.

**Comment by thesadru** [comment]
Seems like I accidentally left in syntax that's only allowed by python 3.9, If you want to quickly fix it just remove the whole `dict[str,Any]`, I'll be making a patch soon.

**Comment by thesadru** [comment]
Just fixed in https://github.com/thesadru/animethemes-dl/commit/cd992325277d6551404355c1399dec9cc60fc31b, so it should be working now. You can reopen this issue if there's still a problem even after updating.
