### ISSUE TITLE
Can't download: KeyError: Resource

### ISSUE THREAD

**Issue by Alpha-Cyberus** [thesadru/animethemes-dl#16]
Hello, I don't know Python well so I've been trying to figure it out and fix the problem myself but am super stuck. 

Using: Windows 10, Python 3.9.5

animethemes-dl alpha_cyberus -a C:\Users\petad\Music\Anime --range 1 2 --coverart
(Put in the range because I want to test that it works with a single show before pulling the music out of a whole block of my list. The anime its looking at is Cestvs: The Roman Fighter)

Traceback (most recent call last):
  File "C:\Python39\Scripts\animethemes-dl-script.py", line 35, in <module>
    sys.exit(load_entry_point('animethemes-dl==2.2.2.4', 'console_scripts', 'animethemes-dl')())
  File "c:\python39\lib\site-packages\animethemes_dl\main.py", line 444, in main
    batch_download(options)
  File "c:\python39\lib\site-packages\animethemes_dl\downloader.py", line 158, in batch_download
    data = get_download_data(
  File "c:\python39\lib\site-packages\animethemes_dl\parsers\dldata.py", line 258, in get_download_data
    raw = get_animethemes(username, site, **animelist_args)
  File "c:\python39\lib\site-packages\animethemes_dl\parsers\parser.py", line 22, in get_animethemes
    return fetch_animethemes(titles)
  File "c:\python39\lib\site-packages\animethemes_dl\parsers\animethemes.py", line 145, in fetch_animethemes
    anime = ft_anime.result()
  File "c:\python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "c:\python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "c:\python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\python39\lib\site-packages\animethemes_dl\parsers\animethemes.py", line 83, in fetch_anime
    anime = verify_anime(data['search']['anime'],alid,alsite)
  File "c:\python39\lib\site-packages\animethemes_dl\parsers\animethemes.py", line 67, in verify_anime
    for resource in anime['resources']:
KeyError: 'resources'

If I understand the code right, it's supposed to connect to the Resource API endpoint of animethemes.moe but when I look at the returned value in animethemes.py line 51  r = session.get(URL.format(title)) using print(r.text), it returns the following dictionaries: search{ anime, artists, entries, series, songs, synonyms, themes, videos}. I don't know if Resources is meant to have been returned as part of this dictionary or as another one?

**Comment by thesadru** [comment]
I've abandoned this project as it's against animethemes' tos and their site doesn't even allow downloading most of the time due to insufficient funds.
